import { expect, test } from './test';
import { documentedTable, renderTable } from '../scripts/contrast-table.mjs';
import { NODE } from './tags';

/**
 * docs/STYLEGUIDE.md's contrast table is generated by scripts/contrast-table.mjs.
 * Compared cell by cell because Prettier pads the columns.
 */
const cells = (table: string | null): string[][] =>
  (table ?? '')
    .split('\n')
    .filter((line) => line.startsWith('|') && !/^\|\s*-/.test(line))
    .map((line) =>
      line
        .split('|')
        .slice(1, -1)
        .map((cell) => cell.trim()),
    );

test('the documented contrast table matches the colour tokens', NODE, () => {
  const documented = documentedTable();
  expect(
    documented,
    'docs/STYLEGUIDE.md has no contrast-table block; run node scripts/contrast-table.mjs --write',
  ).not.toBeNull();
  expect(
    cells(documented),
    'the contrast table has drifted from the tokens; run node scripts/contrast-table.mjs --write',
  ).toEqual(cells(renderTable()));
});

test('every approved pairing meets the ratio its job needs', NODE, () => {
  const failing = cells(renderTable()).filter(
    (row) => row.at(-1) === '**FAIL**',
  );
  expect(failing).toEqual([]);
});
