import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import {
  BLOG_CONTENT_DIR,
  DIST_DIR,
  POST_ROUTES,
  routesFromBuild,
} from './routes';

/**
 * /llms.txt, the Markdown map of the site for a reader that arrived without a
 * browser.
 *
 * The failure it guards is drift, which is silent here in a way the sitemap's
 * is not: a stale sitemap entry gets a 404 somebody's tooling reports, while a
 * stale line here may still resolve with its description wrong, and the only
 * readers are machines. So every link is checked against the routes the build
 * emitted, and the post list is checked for completeness rather than sampled.
 *
 * The placeholder marks are asserted because they are content rather than
 * markup, so nothing else in the suite would notice them go. This file hands
 * post titles and teasers to a reader that cannot tell lorem ipsum from
 * writing. The `placeholder` field they come from is itself held to the text
 * of each post, so a real post left flagged, or a lorem post left unflagged,
 * fails here too.
 *
 * It reads dist/ rather than driving a browser, inside test bodies only; see
 * tests/routes.ts.
 *
 * Proven able to fail, 2026-09-09:
 *
 *   - a route in ROUTE_NOTES the build does not emit fails "every page it
 *     names is a page that exists";
 *   - one post deleted from the Posts section fails "every post is listed",
 *     naming the missing slug;
 *   - every link made relative fails 3 tests: "every link is absolute" as
 *     intended, and both route checks, which parse each link with `new URL`
 *     and throw on a bare path. Recorded so the extra two are not mistaken for
 *     a second defect.
 *
 * And on 2026-09-13, for the placeholder field:
 *
 *   - `placeholder: false` on a lorem post fails "the placeholder field
 *     matches the text";
 *   - the mark dropped from the endpoint fails "every placeholder post is
 *     marked, and only those".
 */

const LLMS_TXT = join(DIST_DIR, 'llms.txt');

const llmsTxt = (): string => {
  expect(
    existsSync(LLMS_TXT),
    `${LLMS_TXT} was not built. It is generated by src/pages/llms.txt.ts.`,
  ).toBe(true);

  return readFileSync(LLMS_TXT, 'utf8');
};

const PLACEHOLDER_MARK = '(placeholder)';

/*
 * Words from the lorem ipsum passage that no real post here uses. Two in a
 * title and teaser is lorem; one could be a real post mentioning the phrase.
 */
const LOREM_WORDS =
  /\b(lorem|ipsum|dolor|consectetur|adipiscing|eiusmod|tempor|incididunt|labore|veniam|nostrud|exercitation|ullamco|laboris|aliquip|commodo|consequat|irure|reprehenderit|voluptate|cillum|fugiat|pariatur|excepteur|occaecat|cupidatat|proident|officia|deserunt|mollit|perspiciatis|voluptatem|quisquam|quibusdam|temporibus|nemo)\b/gi;
const LOREM_THRESHOLD = 2;

interface PostSource {
  slug: string;
  placeholder: string | undefined;
  text: string;
}

/**
 * The frontmatter fields this spec needs, read with line patterns rather
 * than a YAML parser: Playwright collects in plain Node, and every post
 * writes these fields on one line each.
 */
const postSources = (): PostSource[] =>
  readdirSync(BLOG_CONTENT_DIR)
    .filter((name) => name.endsWith('.md'))
    .map((name) => {
      const source = readFileSync(join(BLOG_CONTENT_DIR, name), 'utf8');
      const field = (key: string): string | undefined =>
        new RegExp(`^${key}:\\s*(.+)$`, 'm').exec(source)?.[1];
      return {
        slug: name.replace(/\.md$/, ''),
        placeholder: field('placeholder'),
        text: `${field('title') ?? ''} ${field('teaser') ?? ''}`,
      };
    });

const looksLorem = (text: string): boolean =>
  (text.match(LOREM_WORDS) ?? []).length >= LOREM_THRESHOLD;

/** Every Markdown link target in the file. */
const links = (source: string): string[] =>
  [...source.matchAll(/\]\(([^)]+)\)/g)].map((match) => match[1]!);

test.describe('llms.txt', () => {
  test('every link is absolute', () => {
    /*
     * A reader that fetched this file may have nothing to resolve a path
     * against: it is handed around as text, with no <base> and no enclosing
     * document to inherit an origin from. A relative link here is not a link.
     */
    for (const link of links(llmsTxt())) {
      expect(
        link.startsWith('https://'),
        `llms.txt links to "${link}", which is relative. A reader that was ` +
          'handed this file as text has no base to resolve it against.',
      ).toBe(true);
    }
  });

  test('every page it names is a page that exists', () => {
    const built = new Set(routesFromBuild());
    const named = links(llmsTxt())
      .map((link) => new URL(link).pathname)
      /*
       * The sitemap and security.txt are deliberately not routes: they are
       * generated files, so `routesFromBuild` does not see them and comparing
       * against it would fail on the two links most worth having.
       */
      .filter(
        (path) => !path.endsWith('.xml') && !path.startsWith('/.well-known'),
      )
      .map((path) => (path === '/' ? '/' : path.replace(/\/$/, '')));

    const missing = named.filter((path) => !built.has(path));

    expect(
      missing,
      'llms.txt names page(s) the build did not emit, so a reader that ' +
        'trusts this file is sent somewhere that is not there: ' +
        missing.join(', '),
    ).toEqual([]);
  });

  test('every post is listed', () => {
    const listed = new Set(
      links(llmsTxt())
        .map((link) => new URL(link).pathname.replace(/\/$/, ''))
        .filter((path) => path.startsWith('/blog/')),
    );

    /*
     * Completeness, not a sample. The point of this file is that a reader can
     * use it instead of crawling, and a post missing from it is a post that
     * reader will never learn exists. POST_ROUTES is itself held to the
     * content directory and to dist/ by tests/routes.ts and a11y.spec.ts, so
     * this transitively checks against the real content.
     */
    const missing = POST_ROUTES.filter((route) => !listed.has(route));

    expect(
      missing,
      'llms.txt does not list every post, so a reader using it instead of ' +
        `crawling will never learn these exist: ${missing.join(', ')}`,
    ).toEqual([]);
  });

  test('the placeholder field matches the text', () => {
    const wrong = postSources()
      .filter(
        ({ placeholder, text }) => placeholder !== String(looksLorem(text)),
      )
      .map(({ slug, placeholder }) => `${slug} (placeholder: ${placeholder})`);

    expect(
      wrong,
      'These posts are flagged the opposite way to what their title and ' +
        'teaser read as. A real post still flagged is hidden from readers ' +
        `as filler; a lorem post unflagged is offered as writing: ${wrong.join(', ')}`,
    ).toEqual([]);
  });

  test('every placeholder post is marked, and only those', () => {
    const text = llmsTxt();
    const lineFor = (slug: string): string =>
      text.split('\n').find((line) => line.includes(`/blog/${slug}/)`)) ?? '';

    const wrong = postSources()
      .filter(
        ({ slug, placeholder }) =>
          lineFor(slug).endsWith(PLACEHOLDER_MARK) !== (placeholder === 'true'),
      )
      .map(({ slug }) => slug);

    expect(
      wrong,
      `llms.txt marks these posts wrongly with ${PLACEHOLDER_MARK}: ${wrong.join(', ')}`,
    ).toEqual([]);

    const anyPlaceholder = postSources().some(
      ({ placeholder }) => placeholder === 'true',
    );
    expect(
      text.includes(`Posts marked ${PLACEHOLDER_MARK}`),
      'The note explaining the placeholder mark should appear exactly while ' +
        'some post carries it.',
    ).toBe(anyPlaceholder);
  });
});
