import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { DIST_DIR, POST_ROUTES, routesFromBuild } from './routes';

/**
 * /llms.txt, the Markdown map of the site for a reader that arrived without a
 * browser.
 *
 * The failure it guards is drift, which is silent here in a way the sitemap's
 * is not: a stale sitemap entry gets a 404 somebody's tooling reports, while a
 * stale line here may still resolve with its description wrong, and the only
 * readers are machines. So every link is checked against the routes the build
 * emitted, and the post list is checked for completeness rather than sampled.
 *
 * The placeholder note is asserted because it is content rather than markup,
 * so nothing else in the suite would notice its removal. Ten of the eleven
 * posts are lorem ipsum (2026-09-11), and this file hands their titles and
 * teasers to a reader that cannot tell filler from writing. Remove the note
 * and this assertion together, in the same commit as the last lorem post.
 *
 * It reads dist/ rather than driving a browser, inside test bodies only; see
 * tests/routes.ts.
 *
 * Proven able to fail, 2026-09-09:
 *
 *   - a route in ROUTE_NOTES the build does not emit fails "every page it
 *     names is a page that exists";
 *   - one post deleted from the Posts section fails "every post is listed",
 *     naming the missing slug;
 *   - the placeholder note removed fails "it warns that most posts are
 *     placeholder";
 *   - every link made relative fails 3 of the 4: "every link is absolute" as
 *     intended, and both route checks, which parse each link with `new URL`
 *     and throw on a bare path. Recorded so the extra two are not mistaken for
 *     a second defect.
 */

const LLMS_TXT = join(DIST_DIR, 'llms.txt');

const llmsTxt = (): string => {
  expect(
    existsSync(LLMS_TXT),
    `${LLMS_TXT} was not built. It is generated by src/pages/llms.txt.ts.`,
  ).toBe(true);

  return readFileSync(LLMS_TXT, 'utf8');
};

/** Every Markdown link target in the file. */
const links = (source: string): string[] =>
  [...source.matchAll(/\]\(([^)]+)\)/g)].map((match) => match[1]!);

test.describe('llms.txt', () => {
  test('every link is absolute', () => {
    /*
     * A reader that fetched this file may have nothing to resolve a path
     * against: it is handed around as text, with no <base> and no enclosing
     * document to inherit an origin from. A relative link here is not a link.
     */
    for (const link of links(llmsTxt())) {
      expect(
        link.startsWith('https://'),
        `llms.txt links to "${link}", which is relative. A reader that was ` +
          'handed this file as text has no base to resolve it against.',
      ).toBe(true);
    }
  });

  test('every page it names is a page that exists', () => {
    const built = new Set(routesFromBuild());
    const named = links(llmsTxt())
      .map((link) => new URL(link).pathname)
      /*
       * The sitemap and security.txt are deliberately not routes: they are
       * generated files, so `routesFromBuild` does not see them and comparing
       * against it would fail on the two links most worth having.
       */
      .filter(
        (path) => !path.endsWith('.xml') && !path.startsWith('/.well-known'),
      )
      .map((path) => (path === '/' ? '/' : path.replace(/\/$/, '')));

    const missing = named.filter((path) => !built.has(path));

    expect(
      missing,
      'llms.txt names page(s) the build did not emit, so a reader that ' +
        'trusts this file is sent somewhere that is not there: ' +
        missing.join(', '),
    ).toEqual([]);
  });

  test('every post is listed', () => {
    const listed = new Set(
      links(llmsTxt())
        .map((link) => new URL(link).pathname.replace(/\/$/, ''))
        .filter((path) => path.startsWith('/blog/')),
    );

    /*
     * Completeness, not a sample. The point of this file is that a reader can
     * use it instead of crawling, and a post missing from it is a post that
     * reader will never learn exists. POST_ROUTES is itself held to the
     * content directory and to dist/ by tests/routes.ts and a11y.spec.ts, so
     * this transitively checks against the real content.
     */
    const missing = POST_ROUTES.filter((route) => !listed.has(route));

    expect(
      missing,
      'llms.txt does not list every post, so a reader using it instead of ' +
        `crawling will never learn these exist: ${missing.join(', ')}`,
    ).toEqual([]);
  });

  test('it warns that most posts are placeholder', () => {
    /*
     * The one assertion here about content rather than structure. This file
     * hands a machine the titles and teasers of the lorem ipsum posts, and
     * without the warning it cannot tell filler from writing. Delete this test
     * in the same commit as the last lorem post, not before and not alone.
     */
    expect(
      llmsTxt().toLowerCase(),
      'llms.txt no longer warns that some posts are placeholder. If the ' +
        'lorem posts are gone, remove the note and this test together. If ' +
        'they are not, this file is inviting a reader to quote Latin filler ' +
        'as though it were writing.',
    ).toContain('placeholder');
  });
});
