import { readdirSync, existsSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Every route the site builds.
 *
 * Hardcoded deliberately. Playwright collects test files before the `webServer`
 * command runs, so reading `dist/` at import time would read a stale or absent
 * build and silently produce an empty suite. The list is kept honest by the
 * "route coverage" test in a11y.spec.ts, which reads the real build output and
 * fails if this array and `dist/` have drifted apart.
 *
 * Add a route here when you add a page.
 *
 * `/404` is in the list so the page is scanned and measured like any other,
 * and `astro preview` does serve it at that path with a 200. That is NOT what
 * proves the 404 works: preview is serving the file directly, and it would do
 * that whether or not unknown paths ever reach it. tests/not-found.spec.ts
 * asserts the status code on a path that does not exist, which is the part
 * that can actually regress.
 *
 * The blog routes are split into three named groups rather than listed as one
 * flat block. They are all `/blog/…` and they are generated by three different
 * files, so a route landing in the wrong group is a real mistake this shape
 * makes visible: `/blog/travel` reads as a post slug until it is sitting under
 * CATEGORY_ROUTES. The groups also give the pagination guard below something
 * to count, which a flat list could not do without re-deriving the split.
 */
const PAGE_ROUTES = ['/', '/404', '/about', '/career', '/contact'] as const;

/**
 * Category listings, from `src/pages/blog/[category]/index.astro`. One per
 * entry in BLOG_CATEGORIES (`src/content.config.ts`).
 */
export const CATEGORY_ROUTES = [
  '/blog/skincare',
  '/blog/travel',
  '/blog/personal-thoughts',
  '/blog/professional-journey',
  '/blog/open-source',
] as const;

/** Posts, from `src/pages/blog/[slug].astro`. Newest first. */
export const POST_ROUTES = [
  '/blog/lorem-ipsum-dolor-sit-amet',
  '/blog/consectetur-adipiscing-elit',
  '/blog/ut-enim-ad',
  '/blog/quis-nostrud-exercitation-ullamco',
  '/blog/duis-aute-irure-dolor',
  '/blog/excepteur-sint-occaecat',
  '/blog/sed-ut-perspiciatis-unde-omnis',
  '/blog/nemo-enim-ipsam-voluptatem',
  '/blog/neque-porro-quisquam-est',
  '/blog/at-vero-eos-et-accusamus',
  '/blog/temporibus-autem-quibusdam',
] as const;

/**
 * The blog index. Page 1 is `/blog` (`src/pages/blog/index.astro`); every
 * later page is `/blog/page/<n>` (`src/pages/blog/page/[page].astro`).
 *
 * `/blog/page/2` existing at all is the point of seeding eleven posts: the
 * index paginates at nine, so ten would have been the minimum and eleven
 * leaves the second page with something on it other than a single card.
 *
 * The extra `page` segment is not decoration. `/blog/[category]` and
 * `/blog/[slug]` already share the one segment after `/blog`, so a flat
 * `/blog/2` would put a third dynamic route on it and any numeric category or
 * post slug would collide with a page number.
 */
export const INDEX_ROUTES = ['/blog', '/blog/page/2'] as const;

export const ROUTES = [
  ...PAGE_ROUTES,
  ...INDEX_ROUTES,
  ...CATEGORY_ROUTES,
  ...POST_ROUTES,
] as const;

/**
 * The blog index page size, duplicated from `POSTS_PER_PAGE` in
 * `src/lib/blog.ts`.
 *
 * It has to be duplicated rather than imported. Playwright collects this file
 * in plain Node, with no Astro or Vite in the chain, so anything that reaches
 * `astro:content` fails at collection time and takes the whole suite with it.
 * The pagination test in `tests/blog.spec.ts` counts the cards the built pages
 * actually render, so a copy that drifted from the real value fails there
 * rather than sitting here being quietly wrong.
 */
export const POSTS_PER_PAGE = 9;

export const DIST_DIR = 'dist';

/** Where the Markdown lives. Mirrors BLOG_CONTENT_DIR in src/content.config.ts. */
export const BLOG_CONTENT_DIR = 'src/content/blog';

/**
 * The post routes the Markdown in `src/content/blog/` should produce.
 *
 * A second guard, at a different altitude from `routesFromBuild` below. That
 * one compares this file to `dist/`, so it answers "did the build emit what
 * this list claims". This one compares this file to the *source*, and it
 * answers a question the build cannot: whether a post was added or renamed
 * without POST_ROUTES following it. Both fail on the same mistake; this one
 * names the file rather than the URL, which is where the fix is.
 *
 * Astro's `glob()` loader derives an entry id from the path with the extension
 * stripped, and every post here is a flat `<slug>.md`, so the mapping is the
 * basename. A post in a subdirectory would break that assumption, and this
 * would fail rather than quietly diverge.
 */
export const postRoutesFromContent = (
  contentDir = BLOG_CONTENT_DIR,
): string[] => {
  if (!existsSync(contentDir)) {
    throw new Error(`Blog content not found at "${contentDir}".`);
  }

  return readdirSync(contentDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .map((entry) => `/blog/${entry.name.replace(/\.md$/, '')}`)
    .sort();
};

/**
 * Routes actually present in the build output, derived from its HTML files.
 *
 * Two shapes, because Astro emits two. Every ordinary page is written as
 * `<route>/index.html`, and the route is the directory. `src/pages/404.astro`
 * is special-cased by Astro and written as `dist/404.html` at the root, which
 * is the filename Cloudflare Pages looks for when nothing matches a request.
 * Matching only `index.html` would leave the 404 page out of this list
 * entirely, so the coverage test would have kept passing with `/404` in ROUTES
 * removed, or with the page itself deleted.
 */
const builtPages = (distDir = DIST_DIR): { route: string; file: string }[] => {
  if (!existsSync(distDir)) {
    throw new Error(
      `Build output not found at "${distDir}". Run \`npm run build\` first.`,
    );
  }

  const found: { route: string; file: string }[] = [];

  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);

      if (entry.isDirectory()) {
        walk(full);
        continue;
      }

      if (!entry.name.endsWith('.html')) continue;

      const segments = relative(distDir, full).split(sep);

      if (entry.name === 'index.html') {
        const rel = segments.slice(0, -1).join('/');
        found.push({ route: rel === '' ? '/' : `/${rel}`, file: full });
        continue;
      }

      segments[segments.length - 1] = entry.name.replace(/\.html$/, '');
      found.push({ route: `/${segments.join('/')}`, file: full });
    }
  };

  walk(distDir);

  return found;
};

export const routesFromBuild = (distDir = DIST_DIR): string[] =>
  builtPages(distDir)
    .map((page) => page.route)
    .sort();

/**
 * The routes whose built HTML carries a hydrated island for `component`.
 *
 * This is the completeness guard for a route-list literal that names a subset
 * of ROUTES: a spec that walks `['/']` because that is where the badge used to
 * be keeps passing when a second badge lands somewhere else, and the new one
 * has no coverage at all. Deriving the real list from `dist/` and asserting the
 * literal against it turns that from a silent gap into a failure. See
 * `BADGE_ROUTES` in tests/motion.spec.ts, and `GOLD_ROUTE_CONTROLS` in
 * tests/gold-surface.spec.ts for the same idea applied to a count.
 *
 * The literal cannot simply be replaced by this function. Playwright collects
 * test files before the `webServer` command runs, so a `for` loop over a call
 * to this at module scope would read an absent or stale `dist/` and generate
 * the wrong tests, or none. Same reason ROUTES is hardcoded; same fix.
 *
 * Matched on Astro's `component-url` attribute rather than on the component
 * name anywhere in the page, so a mention of "SpinBadge" in an HTML comment or
 * in prose cannot make a route look like it renders one.
 */
export const islandRoutesFromBuild = (
  component: string,
  distDir = DIST_DIR,
): string[] => {
  const marker = new RegExp(`component-url="[^"]*/${component}\\.[^"]*\\.js"`);

  return builtPages(distDir)
    .filter((page) => marker.test(readFileSync(page.file, 'utf8')))
    .map((page) => page.route)
    .sort();
};
