import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { DIST_DIR } from './routes';
import { configuredSite } from './source';

/**
 * /.well-known/security.txt, per RFC 9116.
 *
 * The failure this file exists for is the expiry. Every other field is wrong
 * loudly or not at all: a missing `Contact` is visible the first time anyone
 * opens the file. `Expires` is a date in the future that becomes a date in the
 * past without anybody touching the repository, and a lapsed security.txt is
 * not an error anywhere. The file still serves, still parses, and is simply no
 * longer a claim.
 *
 * So `the published commitment has not lapsed` fails EXPIRY_WARNING_DAYS
 * before the date rather than after it. It can turn CI red on a day nobody
 * changed a line, and that is the cost of the field meaning anything: the
 * alternative is not "no failure", it is the file expiring in production with
 * no signal.
 *
 * The fix when it fires is never to widen the window. Confirm CONTACT_EMAIL is
 * still an address somebody reads, then move EXPIRES forward and say in the
 * commit that the check was made. A build-time `now + 1 year` would end the
 * failures and the only thing the field says, which is that a human still
 * stands behind the address.
 *
 * It reads dist/ rather than driving a browser, inside test bodies only; see
 * tests/routes.ts. The address and the origin are not written down here: the
 * contact is compared against src/lib/contact.ts, which the footer also
 * imports, and the canonical URL against `site` in astro.config.mjs.
 *
 * Proven able to fail, 2026-09-09:
 *
 *   - EXPIRES set inside the warning window fails "the published commitment
 *     has not lapsed", and a past date fails it with the lapsed message;
 *   - EXPIRES set more than a year out fails "the commitment is not longer
 *     than RFC 9116 allows";
 *   - a different address hardcoded in the endpoint, or the `mailto:` scheme
 *     dropped, fails "the contact is the address the site publishes";
 *   - a relative Canonical fails "the canonical URL is absolute and ours".
 *
 * One mutation is not possible, recorded so it is not attempted again: editing
 * src/lib/contact.ts and leaving dist/ alone passes, because
 * `webServer.command` rebuilds before the first test. No spec here can catch a
 * stale build; what they catch is a source that is wrong.
 */

const SECURITY_TXT = join(DIST_DIR, '.well-known', 'security.txt');
const CONTACT_MODULE = 'src/lib/contact.ts';

/**
 * How long before the expiry this starts failing. 60 days is comfortable
 * rather than tight: time to notice, check the mailbox is still read and move
 * the date, without the check blocking an unrelated release at short notice.
 * Widening it is not the fix when it fires.
 */
const EXPIRY_WARNING_DAYS = 60;

/**
 * RFC 9116 section 2.5.5: an expiry more than a year out SHOULD NOT be used.
 */
const MAX_EXPIRY_DAYS = 365;

const DAY_MS = 24 * 60 * 60 * 1000;

const securityTxt = (): string => {
  expect(
    existsSync(SECURITY_TXT),
    `${SECURITY_TXT} was not built. It is generated by ` +
      'src/pages/.well-known/security.txt.ts, not served from public/.',
  ).toBe(true);

  return readFileSync(SECURITY_TXT, 'utf8');
};

/** One field's value, by name. RFC 9116 fields are `Name: value` lines. */
const field = (source: string, name: string): string | null => {
  const match = new RegExp(`^${name}:\\s*(.+)$`, 'im').exec(source);
  return match ? match[1]!.trim() : null;
};

test.describe('security.txt', () => {
  test('declares the two fields RFC 9116 requires', () => {
    const source = securityTxt();

    expect(
      field(source, 'Contact'),
      'RFC 9116 requires Contact. Without it the file answers no question at ' +
        'all: it is the one line telling a finder where to send a report.',
    ).not.toBeNull();

    expect(
      field(source, 'Expires'),
      'RFC 9116 requires Expires. Without it there is no statement that ' +
        'anybody still stands behind the address.',
    ).not.toBeNull();
  });

  test('the contact is the address the site publishes', () => {
    const declared = field(securityTxt(), 'Contact');

    const source = readFileSync(CONTACT_MODULE, 'utf8');
    const match = /CONTACT_EMAIL\s*=\s*['"]([^'"]+)['"]/.exec(source);
    expect(
      match,
      `no CONTACT_EMAIL found in ${CONTACT_MODULE}. The footer and this file ` +
        'both import it so they cannot drift.',
    ).not.toBeNull();

    /*
     * A `mailto:` URI, not a bare address. RFC 9116 wants a URI here, and a
     * bare address is the mistake that parses as something else entirely.
     */
    expect(
      declared,
      `security.txt offers ${declared} while the site publishes ` +
        `${match![1]} in its footer. A Contact nobody reads is worse than no ` +
        'security.txt: it turns "no channel" into "a channel that was ignored".',
    ).toBe(`mailto:${match![1]}`);
  });

  test('the published commitment has not lapsed', () => {
    const declared = field(securityTxt(), 'Expires')!;
    const expires = new Date(declared);

    expect(
      Number.isNaN(expires.getTime()),
      `Expires reads "${declared}", which is not a date any parser will ` +
        'read. RFC 9116 wants an ISO 8601 timestamp.',
    ).toBe(false);

    const daysLeft = Math.floor((expires.getTime() - Date.now()) / DAY_MS);

    /*
     * Two messages, because the two states need different actions: already
     * lapsed is a live defect on the deployed site, approaching is a reminder
     * with weeks of slack. Neither fix is widening EXPIRY_WARNING_DAYS.
     */
    expect(
      daysLeft,
      daysLeft < 0
        ? `security.txt EXPIRED ${-daysLeft} days ago, on ${declared}. It is ` +
            'serving on the live site right now as a commitment nobody is ' +
            'making. Confirm CONTACT_EMAIL is still read, then move EXPIRES in ' +
            'src/pages/.well-known/security.txt.ts forward.'
        : `security.txt expires in ${daysLeft} days, on ${declared}. This ` +
            `fires ${EXPIRY_WARNING_DAYS} days out so there is time to act. ` +
            'Confirm CONTACT_EMAIL is still an address somebody reads, then ' +
            'move EXPIRES forward and say in the commit that the check was ' +
            'made. Do not widen the window.',
    ).toBeGreaterThan(EXPIRY_WARNING_DAYS);
  });

  test('the commitment is not longer than RFC 9116 allows', () => {
    const declared = field(securityTxt(), 'Expires')!;
    const daysOut = Math.floor(
      (new Date(declared).getTime() - Date.now()) / DAY_MS,
    );

    /*
     * The other direction, the one the expiry test invites somebody to reach
     * for. Pushing EXPIRES ten years out silences that test forever and
     * empties the field of meaning.
     */
    expect(
      daysOut,
      `Expires is ${daysOut} days out. RFC 9116 says not more than a year. ` +
        'A distant expiry is the easy way to stop the lapse test failing and ' +
        'it removes the only thing the field asserts.',
    ).toBeLessThanOrEqual(MAX_EXPIRY_DAYS);
  });

  test('the canonical URL is absolute and ours', () => {
    const declared = field(securityTxt(), 'Canonical');
    expect(declared, 'security.txt declares no Canonical').not.toBeNull();

    const site = configuredSite();

    /*
     * RFC 9116 requires an absolute URI. The field exists to let a reader tell
     * whether the copy they hold is the one published at the origin it names,
     * which a path cannot say.
     */
    expect(
      declared,
      `Canonical reads "${declared}". RFC 9116 requires an absolute URI: the ` +
        'field exists so a reader can tell whether this copy is the one ' +
        'published at the origin it names, which a path cannot express.',
    ).toBe(`${site}/.well-known/security.txt`);
  });
});
