/*
 * Fails on a relative Markdown link to a missing path or a missing `#heading`,
 * or a link or code span naming a gitignored path (it exists locally, so an
 * existence check passes). External URLs are not fetched.
 */

import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, posix, relative, resolve } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/* [text](target), ignoring any "title" that follows the target. */
const LINK = /\[[^\]]*\]\(\s*([^)\s]+?)\s*(?:"[^"]*")?\)/g;

/* Resolved against the repository root. */
const CODE_SPAN = /`([^`\n]+)`/g;

/* Gitignored but generated by a documented command. */
const GENERATED = [
  'dist/',
  'coverage/',
  'node_modules/',
  'tmp/umami-upstream.js',
];

/* External, in-page, or a site route: `/blog/<slug>` is not a file path. */
const isUnresolvable = (target) =>
  /^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#)/i.test(target);

/* A slash or `.md` makes a path; a trailing `/` names a location, allowed. */
const pathsInSpan = (span) =>
  span
    .split(/\s+/)
    .map((token) => token.replace(/^['"(]+|['"),.:;]+$/g, ''))
    .filter(
      (token) =>
        (token.includes('/') || token.endsWith('.md')) &&
        !isUnresolvable(token) &&
        !/[*?<>{}$~=[\]]/.test(token),
    )
    .map((token) => token.replace(/:\d+(?:[-–]\d+)?$/, ''));

const markdownFiles = () =>
  execFileSync(
    'git',
    ['ls-files', '-z', '--cached', '--others', '--exclude-standard', '*.md'],
    { cwd: ROOT, encoding: 'utf8' },
  )
    .split('\0')
    .filter((path) => path !== '' && existsSync(join(ROOT, path)));

/* `git check-ignore` exits 1 when nothing is ignored, which is not an error. */
const ignoredAmong = (paths) => {
  if (paths.length === 0) return new Set();
  try {
    const out = execFileSync('git', ['check-ignore', '--stdin'], {
      cwd: ROOT,
      input: paths.join('\n'),
      encoding: 'utf8',
    });
    return new Set(out.split('\n').filter(Boolean));
  } catch (error) {
    if (error.status === 1) return new Set();
    throw error;
  }
};

const lineOf = (source, index) => source.slice(0, index).split('\n').length;

/* GitHub's heading ids (github-slugger): drop all but letters, marks, digits, `_`, `-`, spaces. */
const slug = (text) =>
  text
    .toLowerCase()
    .replace(/[^\p{L}\p{M}\p{N}\p{Pc}\- ]/gu, '')
    .replace(/ /g, '-');

/* What GitHub renders a heading's inline Markdown and HTML to, before slugging. */
const headingText = (raw) =>
  raw
    .replace(/\s+#+\s*$/, '')
    .replace(/<[^>]+>/g, '')
    .replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/`/g, '')
    .replace(/(\*\*|__|\*|\b_|_\b)/g, '')
    .trim();

const FENCE = /^(`{3,}|~{3,})/;
const HEADING = /^#{1,6}\s+(.+)$/;
const HTML_ID = /<a\s[^>]*(?:id|name)="([^"]+)"/g;

/* Every anchor a file offers: heading slugs, numbered like GitHub's, and explicit ids. */
const anchorsIn = (source) => {
  const anchors = new Set();
  const seen = new Map();
  let fence = null;
  for (const line of source.split('\n')) {
    const opener = FENCE.exec(line.trim())?.[1];
    if (opener && (fence === null || line.trim().startsWith(fence))) {
      fence = fence === null ? opener[0].repeat(3) : null;
      continue;
    }
    if (fence !== null) continue;
    const heading = HEADING.exec(line);
    if (heading) {
      const base = slug(headingText(heading[1]));
      const count = seen.get(base) ?? 0;
      anchors.add(count === 0 ? base : `${base}-${count}`);
      seen.set(base, count + 1);
    }
    for (const id of line.matchAll(HTML_ID)) anchors.add(id[1]);
  }
  return anchors;
};

const anchorCache = new Map();
const anchorsOf = async (path) => {
  if (!anchorCache.has(path)) {
    anchorCache.set(path, anchorsIn(await readFile(path, 'utf8')));
  }
  return anchorCache.get(path);
};

/* Only Markdown targets have headings to check; `#L10` on a source file does not. */
const checkFragment = async (where, targetPath, fragment) => {
  if (
    fragment === undefined ||
    fragment === '' ||
    !targetPath.endsWith('.md')
  ) {
    return;
  }
  let id;
  try {
    id = decodeURIComponent(fragment);
  } catch {
    broken.push(`${where}  (malformed %-escape)`);
    return;
  }
  if (!(await anchorsOf(targetPath)).has(id)) {
    broken.push(`${where}  (no heading #${id})`);
  }
};

const broken = [];
const references = [];

for (const file of markdownFiles()) {
  const path = join(ROOT, file);
  const source = await readFile(path, 'utf8');

  for (const match of source.matchAll(LINK)) {
    const target = match[1];
    const where = `${file}:${lineOf(source, match.index)}  ${target}`;

    if (target.startsWith('#')) {
      await checkFragment(where, path, target.slice(1));
      continue;
    }
    if (isUnresolvable(target)) continue;

    const [pathPart, fragment] = target.split('#');
    if (pathPart === '') continue;

    let decoded;
    try {
      decoded = decodeURIComponent(pathPart);
    } catch {
      broken.push(`${where}  (malformed %-escape)`);
      continue;
    }
    const resolved = resolve(dirname(path), decoded);
    if (!existsSync(resolved)) {
      broken.push(where);
      continue;
    }
    await checkFragment(where, resolved, fragment);
    references.push({ where, path: relative(ROOT, resolved) });
  }

  for (const match of source.matchAll(CODE_SPAN)) {
    for (const token of pathsInSpan(match[1])) {
      references.push({
        where: `${file}:${lineOf(source, match.index)}  ${token}`,
        path: posix.normalize(token),
      });
    }
  }
}

const candidates = references.filter(
  ({ path }) =>
    path !== '' &&
    !path.startsWith('..') &&
    !path.endsWith('/') &&
    !GENERATED.some((prefix) => path === prefix || path.startsWith(prefix)),
);
const ignored = ignoredAmong([...new Set(candidates.map(({ path }) => path))]);
const unpublished = candidates
  .filter(({ path }) => ignored.has(path))
  .map(({ where }) => where);

if (broken.length > 0) {
  console.error(`Found ${broken.length} broken relative link(s):\n`);
  for (const failure of broken) console.error(`  ${failure}`);
}

if (unpublished.length > 0) {
  if (broken.length > 0) console.error('');
  console.error(
    `Found ${unpublished.length} reference(s) to a gitignored path, which ` +
      'no reader of the repository can open. State the fact, link an issue, ' +
      'or drop the reference:\n',
  );
  for (const failure of unpublished) console.error(`  ${failure}`);
}

if (broken.length > 0 || unpublished.length > 0) process.exit(1);

console.log(
  'Links: every relative Markdown link and #heading resolves, and no Markdown file names a gitignored path.',
);
